{"uuid": "8ff18b43-5723-4488-ab97-fba3c1289b5a", "children": ["d5b9ef48-4a4f-48cd-8a12-10c3b171db46", "8c1df131-467a-4ab7-92af-5f5265e709f0", "f67e6b2f-67a1-4c3f-96b2-caeb7010eb66", "69a1e747-a90a-457e-91d0-55b77ecf84a8"], "befores": [{"name": "topicchushihua", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../../yaml_operation/yaml_manage/testcase.yaml'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/apple/PycharmProjects/zhongshu_chenyun/Test_Case/Test_APIcase/test_xiaoxixietong.py\", line 32, in topicchushihua\n    with_yaml.write_yaml_fugai(zhi01)\n  File \"/Users/apple/PycharmProjects/zhongshu_chenyun/yaml_operation/with_yaml/with_data.py\", line 69, in write_yaml_fugai\n    with open(self.file, encoding=encoding, mode='w') as f:\n"}, "start": 1621999799945, "stop": 1621999799987}], "start": 1621999799945, "stop": 1621999800203}