{"name": "查询已授权数据接口", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\nOperation_Magage/test_list.py:257: AssumptionFailure\n>>\tpytest.assume(str(result['code']) == '200','失败原因是：%s' %result['message'])\nAssertionError: 失败原因是：请求参数不对，请检查请求形式\nassert False\n\nOperation_Magage/test_list.py:258: AssumptionFailure\n>>\tpytest.assume(result['success'] == True)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               Operation_Magage/test_list.py:257: AssumptionFailure\nE               >>\tpytest.assume(str(result['code']) == '200','失败原因是：%s' %result['message'])\nE               AssertionError: 失败原因是：请求参数不对，请检查请求形式\nE               assert False\nE               \nE               Operation_Magage/test_list.py:258: AssumptionFailure\nE               >>\tpytest.assume(result['success'] == True)\nE               AssertionError: assert False\n\n/usr/local/lib/python3.8/site-packages/six.py:702: FailedAssumption"}, "start": 1621999737517, "stop": 1621999737549, "uuid": "ccde3cd1-1856-4888-8033-31de650cceb8", "historyId": "6b203c664de6b87c73131fb2e6cd0621", "testCaseId": "1e058e1625f1b1c547c4309f0073e11b", "fullName": "Operation_Magage.test_list#test_listshouquandata", "labels": [{"name": "epic", "value": "接入方平台"}, {"name": "parentSuite", "value": "Operation_Magage"}, {"name": "suite", "value": "test_list"}, {"name": "host", "value": "zhouchengjiedeMacBook-Pro.local"}, {"name": "thread", "value": "28577-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Operation_Magage.test_list"}]}