{"name": "查询数据源接口", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\nOperation_Magage/test_list.py:265: AssumptionFailure\n>>\tpytest.assume(str(result['code']) == '200','失败原因是：%s' %result['message'])\nAssertionError: 失败原因是：请求参数不对，请检查请求形式\nassert False\n\nOperation_Magage/test_list.py:266: AssumptionFailure\n>>\tpytest.assume(result['success'] == True)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               Operation_Magage/test_list.py:265: AssumptionFailure\nE               >>\tpytest.assume(str(result['code']) == '200','失败原因是：%s' %result['message'])\nE               AssertionError: 失败原因是：请求参数不对，请检查请求形式\nE               assert False\nE               \nE               Operation_Magage/test_list.py:266: AssumptionFailure\nE               >>\tpytest.assume(result['success'] == True)\nE               AssertionError: assert False\n\n/usr/local/lib/python3.8/site-packages/six.py:702: FailedAssumption"}, "start": 1621999737570, "stop": 1621999737596, "uuid": "494e16d5-2230-4a00-95da-54ac1a300c66", "historyId": "0d3f11efcfce11665c1d159d8da95741", "testCaseId": "64d5d1cd4240e344af79116d36cfb427", "fullName": "Operation_Magage.test_list#test_listshujvyuan", "labels": [{"name": "epic", "value": "接入方平台"}, {"name": "parentSuite", "value": "Operation_Magage"}, {"name": "suite", "value": "test_list"}, {"name": "host", "value": "zhouchengjiedeMacBook-Pro.local"}, {"name": "thread", "value": "28577-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Operation_Magage.test_list"}]}