{"uuid": "06575c5e-a384-423b-90b4-8322cdf364a0", "children": ["1634b216-4d75-4d93-ba82-14d83505568b", "04623b28-db10-426d-bb80-3105e71b5653", "dc1e7e3c-cda6-4e0d-bc88-7926f16018d9", "009500a2-3c59-4cbf-997b-d4df0d1e9045"], "befores": [{"name": "datayuanchushuhua", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../../yaml_operation/yaml_manage/testcase.yaml'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/apple/PycharmProjects/zhongshu_chenyun/Test_Case/Test_APIcase/test_shujvxietong.py\", line 238, in datayuanchushuhua\n    with_yaml.write_yaml_fugai(dict1)\n  File \"/Users/apple/PycharmProjects/zhongshu_chenyun/yaml_operation/with_yaml/with_data.py\", line 69, in write_yaml_fugai\n    with open(self.file, encoding=encoding, mode='w') as f:\n"}, "start": 1621999799783, "stop": 1621999799805}], "start": 1621999799783, "stop": 1621999799853}